import assert from 'node:assert/strict';
import fs from 'node:fs';
let adds=0,removes=[];
globalThis.addActorCondition=async(a,id,o)=>{adds++;a.system.conditions.push({id:`new${adds}`,conditionId:id,...o});};
globalThis.removeActorCondition=async(a,id)=>{removes.push(id);a.system.conditions=a.system.conditions.filter(c=>c.id!==id);};
const a={uuid:'Actor.a',name:'A',type:'character',system:{conditions:[{id:'crit',conditionId:'disoriented',sourceId:'critical:1'}]}};
const b={uuid:'Scene.s.Token.b.Actor.b',name:'B',type:'character',system:{conditions:[]}};
const scene={tokens:{contents:[{actor:a,name:'A token'},{actor:b,name:'B token'}]}};
globalThis.game={user:{id:'gm',isGM:true},users:{activeGM:{id:'gm'}},actors:{contents:[a]},genesysEncounterRecovery:{recover:async ref=>{if(ref==='bad')throw Error('already recovered');}}};
let source=fs.readFileSync('dist/module/gm-health.js','utf8').replace(/^import .*;$/gm,'');
source='const CORE_CONDITIONS=[{id:"disoriented"}];\n'+source;
const {healthRoster,applyHealthBatch,recoverHealthBatch}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
assert.equal(healthRoster(scene).length,2);assert.equal(healthRoster(scene)[0].scope,'Scene');
await applyHealthBatch([a.uuid,a.uuid,b.uuid],{operation:'add',conditionId:'disoriented',scene});assert.equal(adds,2);
await applyHealthBatch([a.uuid],{operation:'add',conditionId:'disoriented',scene});assert.equal(adds,2);
await applyHealthBatch([a.uuid],{operation:'remove',conditionId:'disoriented',scene});assert.deepEqual(removes,['new1']);assert.equal(a.system.conditions[0].id,'crit');
await assert.rejects(applyHealthBatch(['missing'],{operation:'add',conditionId:'disoriented',scene}),/unavailable/);
const result=await recoverHealthBatch(['ok','bad','ok'],'cool',scene);assert.equal(result.applied.length,1);assert.equal(result.failed.length,1);
game.user.isGM=false;assert.deepEqual(healthRoster(scene),[]);await assert.rejects(applyHealthBatch([a.uuid],{operation:'add',conditionId:'disoriented',scene}),/active GM/);
console.log('PASS health roster, deduplication, source protection, recovery partial failure, permissions');
