import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {installDefaultActions,ACTION_BINDINGS} from '../dist/module/action-defaults.js';
let pack;
globalThis.Hooks={once(){}};
const source=fs.readFileSync('dist/module/content-packs/realms-of-terrinoth-heroic-motivations.js','utf8');
const ids=[...source.matchAll(/primary\("([^"]+)", "([^"]+)", (\d+)\)/g)].map(m=>({id:`rot-heroic:${m[1]}`,label:m[2],kind:'primary-effect',metadata:{printedSource:`Realms of Terrinoth p. ${m[3]}`}}));
assert.equal(ids.length,11);
const items=[];globalThis.game={user:{id:'gm',isGM:true},users:{activeGM:{id:'gm'}},folders:{contents:[{id:'f',name:'Actions',type:'Item'}]},items:{contents:items},genesysContent:{getContent:()=>ids}};
globalThis.foundry={documents:{Item:{create:async d=>{items.push(d);return d;}}}};
assert.equal(await installDefaultActions(),14);assert.equal(await installDefaultActions(),0);
assert.equal(items.filter(i=>i.system.binding==='heroic').length,11);
assert.ok(items.filter(i=>i.system.binding==='heroic').every(i=>ids.some(r=>r.id===i.system.heroicId)));
items.splice(items.findIndex(i=>i.system.binding==='assist'),1);
assert.equal(await installDefaultActions({heroicOnly:true}),0);assert.equal(items.some(i=>i.system.binding==='assist'),false);
const code=fs.readFileSync('dist/module/character-sheet-actions-tab.js','utf8');
let calls=0,warnings=[];
const actor={id:'a',isOwner:true,system:{heroicAbility:{primaryEffectId:ids[0].id}}};
const action={id:'x',binding:'heroic',heroicId:ids[0].id};
const button={disabled:false,dataset:{customActionUse:'x'},closest:()=>({})};
const c=vm.createContext({ACTION_BINDINGS,event:{target:{closest:()=>button},preventDefault(){}},actorForRoot:()=>actor,customActions:()=>[action],game:{user:{isGM:true},genesysHeroicLive:{requestActivation:async()=>calls++}},ui:{notifications:{warn:e=>warnings.push(e)}}});
const handler=code.slice(code.indexOf('    const use=event.target'),code.indexOf('    const general=event.target'));
await vm.runInContext(`(async()=>{${handler}})()`,c);assert.equal(calls,1);
action.heroicId='different';await vm.runInContext(`(async()=>{${handler}})()`,c);assert.equal(calls,1);assert.equal(warnings.length,1);
console.log('PASS 11 Heroic Items, idempotent install and owned ability routing');
