import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {primaryRank} from '../dist/domain/heroic/primary-effects.js';
let maneuvers=0,failTarget=false;
globalThis.__unleash={primaryRank,useSceneTurnManeuver:async()=>{maneuvers++;}};
const source=(await fs.readFile(new URL('../dist/module/heroic-unleash.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
const {resolveUnleash}=await import('data:text/javascript;base64,'+Buffer.from('const {primaryRank,useSceneTurnManeuver}=globalThis.__unleash;\n'+source).toString('base64'));
const make=(uuid,system)=>({uuid,system,flags:{},getFlag(_s,k){return this.flags[k];},async update(data){if(uuid==='target'&&failTarget){failTarget=false;throw Error('target failed');}for(const[k,v]of Object.entries(data)){if(k.startsWith('flags.genesys-vtt.'))this.flags[k.slice(18)]=structuredClone(v);if(k==='system.wounds.value')this.system.wounds.value=v;if(k==='system.minionGroup.casualties')this.system.minionGroup.casualties=v;}}});
const actor=make('hero',{heroicAbility:{active:true,primaryEffectId:'rot-heroic:unleash',powerLevel:'base'}});
actor.flags.heroicTiming={activationId:'a',sceneId:'s',encounterId:'e'};
const target=make('target',{role:'minion',minionGroup:{members:3,memberWoundThreshold:4},wounds:{value:0}});
const token={id:'t',parent:{id:'s'},actor:target,x:0,y:0,elevation:0,name:'Minions'};
const state={status:'active',round:1,activeActorRef:'hero'};
globalThis.canvas={scene:{id:'s',getFlag:()=> 'e',tokens:new Map([['t',token]])}};
globalThis.game={user:{id:'gm',isGM:true,targets:new Set([{document:token}])},users:{activeGM:{id:'gm'}},genesysVtt:{initiative:{sceneState:()=>state}}};
globalThis.ui={notifications:{info(){}}};
globalThis.foundry={applications:{api:{DialogV2:{confirm:async()=>true}}}};
failTarget=true;await assert.rejects(resolveUnleash(actor),/target failed/);assert.equal(maneuvers,1);
await resolveUnleash(actor);assert.equal(maneuvers,1,'retry does not charge another maneuver');assert.equal(target.system.minionGroup.casualties,3);
await assert.rejects(resolveUnleash(actor),/already used/);
state.round=2;actor.system.heroicAbility.powerLevel='improved';await resolveUnleash(actor);assert.equal(maneuvers,1,'Improved is incidental');
game.user.isGM=false;await assert.rejects(resolveUnleash(actor),/GM/);
console.log('PASS: Unleash once per round, target-save retry without repeat maneuver, Improved incidental and GM authority');
