import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const data=JSON.parse(fs.readFileSync('data/journals-v1889.json'));
assert(!/[åäöÅÄÖ]/.test(JSON.stringify(data)));
const callbacks={},settings={},values={};let creates=0,failAt=4,rendered=0;
globalThis.Hooks={once:(k,f)=>callbacks[k]=f,on(){}};
globalThis.game={user:{id:'gm',isGM:true},users:{activeGM:{id:'gm'}},folders:[],journal:[],settings:{get:(_s,k)=>values[k],register:(_s,k,v)=>settings[k]=v}};
globalThis.fetch=async()=>({ok:true,json:async()=>structuredClone(data)});
globalThis.Folder={create:async d=>{const f={...d,id:'f'};game.folders.push(f);return f;}};
globalThis.JournalEntry={create:async d=>{const j={...d,id:`j${game.journal.length}`,pages:[],testUserPermission:()=>true,sheet:{render:()=>++rendered},async createEmbeddedDocuments(type,rows){assert.equal(type,'JournalEntryPage');if(++creates===failAt)throw Error('interrupted');for(const r of rows){const p={...r,async update(d){Object.assign(this,d);},async delete(){j.pages.splice(j.pages.indexOf(this),1);}};j.pages.push(p);}}};game.journal.push(j);return j;}};
const api=await import('../dist/module/rules-journals-v1889.js');callbacks.init();assert.equal(Object.keys(settings).length,2);
await assert.rejects(api.installJournals(),/interrupted/);
failAt=-1;await Promise.all([api.installJournals(),api.installJournals()]);assert.equal(game.journal.length,3);assert.equal(game.folders.length,1);assert.equal(game.journal.reduce((n,j)=>n+j.pages.length,0),32);
const core=game.journal[0],terrinoth=game.journal[1];core.pages[0].text.content='GM edit';core.ownership.default=0;
await api.installJournals();assert.equal(core.pages[0].text.content,'GM edit');assert.equal(core.ownership.default,0);assert.equal(core.pages.length,9);
values.coreRulesPdf='worlds/test/core.pdf';values.terrinothRulesPdf='worlds/test/terrinoth.pdf';await api.installJournals();assert.equal(core.pages.length,10);assert.equal(terrinoth.pages.length,8);const pdf=core.pages.at(-1);assert.equal(pdf.type,'pdf');
values.coreRulesPdf='worlds/test/new-core.pdf';await api.installJournals();assert.equal(core.pages.at(-1),pdf);assert.equal(pdf.src,values.coreRulesPdf);
values.coreRulesPdf='javascript:bad.pdf';await assert.rejects(api.syncPdf('core'),/Choose a PDF/);assert.equal(pdf.src,'worlds/test/new-core.pdf');
values.coreRulesPdf='';await api.installJournals();assert.equal(core.pages.length,9);assert.equal(terrinoth.pages.length,8);
game.user={id:'player',isGM:false};assert.equal(await api.installJournals(),false);await api.openJournal('manual');assert.equal(rendered,1);core.testUserPermission=()=>false;await assert.rejects(api.openJournal('core'),/not shared/);
game.user={id:'other-gm',isGM:true};assert.equal(await api.installJournals(),false);
// Execute the real navigation handler with a DOM geometry double: the regression was its allowlist.
const source=fs.readFileSync('dist/module/apps/gm-dock-v1830.js','utf8');const body=source.match(/static #navigateSection\(event, target\) \{([\s\S]*?)\n  \}/)[1];let scroll;
const context={requireGm:()=>true};const navigate=vm.runInNewContext(`(function(event,target){${body}})`,context);
const content={scrollTop:50,getBoundingClientRect:()=>({top:10}),scrollTo:o=>scroll=o};const root={querySelector:selector=>selector==='#genesys-gm-rules'?{getBoundingClientRect:()=>({top:300})}:selector==='.window-content'?content:{getBoundingClientRect:()=>({height:40})}};
navigate.call({element:root},{preventDefault(){},stopPropagation(){}},{dataset:{section:'genesys-gm-rules'}});assert.equal(scroll.top,292);assert.equal(scroll.behavior,'auto');
scroll=null;navigate.call({element:root},{},{dataset:{section:'untrusted'}});assert.equal(scroll,null);
console.log('PASS partial-install recovery, concurrent idempotence, preserved edits/ownership, PDF create/update/remove, authority, reader opening and actual Rules navigation');
