import assert from 'node:assert/strict';
import {RUNE_RULES,runeMagicPlan,runeDiscount} from '../dist/domain/runes/runes.js';
assert.equal(Object.keys(RUNE_RULES).length,17);
const shard=id=>({contentId:id,tags:['runebound-shard']});
const selection=(id,difficulty,count=1)=>({effect:{id,difficulty},count});
assert.throws(()=>runeMagicPlan(shard('arcane-bolt-rune'),'arcana','attack'),/only for Runes/);
let plan=runeMagicPlan(shard('ice-storm-rune'),'runes','attack');assert.deepEqual(plan.effects,{ice:1,blast:1});assert.equal(runeDiscount(plan,[selection('ice',1),selection('blast',1)]),2);
plan=runeMagicPlan(shard('teleportation-rune'),'runes','attack');assert.equal(runeDiscount(plan,[selection('range',1,4)]),3);assert.equal(runeDiscount(plan,[selection('range',1,4)],new Set(['range'])),2);
plan=runeMagicPlan({...shard('lesser-rune'),boundEffectId:'range'},'runes','attack');assert.equal(runeDiscount(plan,[selection('range',1,3)]),1);assert.throws(()=>runeDiscount(plan,[selection('range',2)]),/difficulty-one/);
assert.equal(runeMagicPlan(shard('rune-of-collection'),'runes','barrier').strainCost,1);
assert.deepEqual(runeMagicPlan(shard('sunburst-rune'),'runes','attack').forced,['holy']);
globalThis.Hooks={once(){}};let serial=0;globalThis.foundry={utils:{randomID:()=>`rune${++serial}`}};
const write=(obj,patch)=>{for(const [key,v]of Object.entries(patch)){let t=obj;const ps=key.split('.');for(const p of ps.slice(0,-1))t=t[p]??={};t[ps.at(-1)]=structuredClone(v);}};
const flag=function(_s,k){return this.flags?.['genesys-vtt']?.[k];};
const items=new Map();items[Symbol.iterator]=function*(){yield* this.values();};
const makeRune=id=>({id,name:id,type:'implement',system:{tags:['runebound-shard']},getFlag:(_s,k)=>k==='contentId'?id:null});for(const id of ['blasting-rune','stasis-rune','wanderers-stone'])items.set(id,makeRune(id));
let failCreate=true;
const actor={uuid:'Actor.a',type:'character',system:{role:'pc',strain:{value:8,threshold:12},wounds:{value:0,threshold:12},skills:[],conditions:[]},items,getFlag:flag,async update(p){write(this,p);},async createEmbeddedDocuments(_t,rows){if(failCreate){failCreate=false;throw Error('item interrupted');}for(const data of rows){const doc={...data,id:`weapon${serial}`,getFlag:flag};items.set(doc.id,doc);}},async deleteEmbeddedDocuments(_t,ids){for(const id of ids)items.delete(id);}};
const target={...actor,uuid:'Actor.t',system:structuredClone(actor.system),items:new Map()};
const current={status:'active',round:1,turnNumber:1,activeActivationId:'base',activeActorRef:actor.uuid};const scene={id:'s',getFlag:()=> 'encounter'};
globalThis.game={user:{isGM:true,id:'gm'},users:{activeGM:{id:'gm'}},genesysVtt:{initiative:{resolveActorRef:ref=>ref===actor.uuid?actor:ref===target.uuid?target:null,sceneState:()=>current}}};
const {activateRune,finishRuneTurn}=await import('../dist/module/rune-activation-v1888.js');
await assert.rejects(activateRune(actor,{confirmed:true,revision:0,itemId:'blasting-rune'},scene),/item interrupted/);await activateRune(actor,{},scene);assert.equal(items.size,4);assert.equal([...items].find(i=>i.type==='weapon').system.skillId,'discipline');assert.equal(actor.system.skills.length,0);
await finishRuneTurn(actor,current,scene);assert.equal(items.size,3);
await activateRune(actor,{confirmed:true,revision:1,itemId:'stasis-rune',targetRefs:[target.uuid]},scene);assert.equal(actor.system.strain.value,10);assert.equal(target.system.conditions.length,2);
await finishRuneTurn(target,{...current,activeActorRef:target.uuid,turnNumber:2},scene);assert.equal(target.system.conditions.length,0);
await activateRune(actor,{confirmed:true,revision:2,itemId:'wanderers-stone'},scene);assert.equal(actor.system.strain.value,5);
await assert.rejects(activateRune(actor,{confirmed:true,revision:3,itemId:'wanderers-stone'},scene),/already used/);
console.log('PASS 17 shard profiles, separate trained implement rules, forced/free effects, costs, untrained Discipline weapon activation, retry, expiry and once-per-encounter healing');
const {beginRuneTurn}=await import('../dist/module/rune-activation-v1888.js');
write(target,{'system.conditions':[{id:'misery',conditionId:'disoriented',active:true}],'flags.genesys-vtt.runeDurations':[{id:'misery',sceneId:scene.id,expiresRound:4}]});
await beginRuneTurn(target,{...current,round:3},scene);assert.equal(target.system.conditions.length,1);await beginRuneTurn(target,{...current,round:4},scene);assert.equal(target.system.conditions.length,0,'round duration expires before fourth-round check, not after it');
console.log('PASS rune round expiry occurs before the next out-of-duration check');
